<?php

return [
    [
        'id' => 7,
        'title' => 'The database can be avoided',
        'summary' => 'Why we should think before adding the database as a dependency.',
        'slug' => 'the-database-can-be-avoided',
        'published_at' => '2019-12-14 22:50',
        'modified_at' => '2019-12-14 22:50',
        'image_url' => '/blog-img/7.jpg',
        'image_width' => 1300,
        'image_height' => 700,
        'subjects' => ['Database', 'Open Source', 'Coding'],
    ],
    [
        'id' => 6,
        'title' => 'Hello World!',
        'summary' => 'I am very happy to announce the release of my personal website!',
        'slug' => 'hello-world',
        'published_at' => '2013-11-25 13:00',
        'modified_at' => '2019-12-08 13:00',
        'image_url' => '/blog-img/6.jpg',
        'image_width' => 1300,
        'image_height' => 700,
        'subjects' => ['Introduction'],
    ],
    [
        'id' => 5,
        'title' => 'Git repository inside composer vendors',
        'summary' => 'How to use git when developing a laravel package.',
        'slug' => 'git-repository-inside-composer-vendors',
        'published_at' => '2014-02-08 13:00',
        'modified_at' => '2014-02-08 13:00',
        'image_url' => '/blog-img/5.jpg',
        'image_width' => 1300,
        'image_height' => 700,
        'subjects' => ['PHP', 'Composer', 'Git', 'PhpStorm'],
    ],
    [
        'id' => 4,
        'title' => 'How to reduce AWS S3 costs by caching pictures locally',
        'summary' => 'I wanted to use S3 as a storage and backup, but I didn\'t want to get additionally '.
            'charged from AWS S3 for the pictures bandwidth.',
        'slug' => 'how-to-reduce-aws-s3-costs-by-caching-pictures-locally',
        'published_at' => '2017-04-23 13:00',
        'modified_at' => '2017-04-23 13:00',
        'image_url' => '/blog-img/4.jpg',
        'image_width' => 1300,
        'image_height' => 867,
        'subjects' => ['PHP', 'nginx', 'AWS', 'S3', 'Laravel'],
    ],
    [
        'id' => 3,
        'title' => 'Testing a live site with Laravel Dusk using Docker Compose ',
        'summary' => 'Sharing how you can quickly install and run Laravel Dusk for testing your project using Docker.',
        'slug' => 'testing-a-live-site-with-laravel-dusk-using-docker-compose',
        'published_at' => '2017-05-05 13:00',
        'modified_at' => '2017-05-05 13:00',
        'image_url' => '/blog-img/3.jpg',
        'image_width' => 1300,
        'image_height' => 612,
        'subjects' => ['PHP', 'docker', 'Laravel', 'dusk', 'selenium'],
    ],
    [
        'id' => 2,
        'title' => 'The end of ad based TV?',
        'summary' => 'I share my concerns about TV commercials targeted to children and the future of TV as we know it.',
        'slug' => 'the-end-of-ad-based-tv',
        'published_at' => '2019-12-07 13:00',
        'modified_at' => '2019-12-07 13:00',
        'image_url' => '/blog-img/2.jpg',
        'image_width' => 1300,
        'image_height' => 844,
        'subjects' => ['commercials', 'parenting', 'tv'],
    ],
    [
        'id' => 1,
        'title' => 'How to use Vue.js on jQuery legacy websites',
        'summary' => 'One of the reasons it was very hard for me to start using Vue is '.
            'because I was coding on existing websites whose frontend was built with jQuery.',
        'slug' => 'how-i-use-vuejs-on-jquery-legacy-websites',
        'published_at' => '2019-12-04 12:00',
        'modified_at' => '2019-12-04 16:00',
        'image_url' => '/blog-img/1.jpg',
        'image_width' => 1300,
        'image_height' => 844,
        'subjects' => ['jQuery', 'Vue.js'],
    ],

];
